### ISSUE TITLE
DevOps Setup for BELMgr

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#2]
Can you set up http://belmgr.belframework.org and add this to Bamboo to deploy this app to a server with that domain?  

We could run this completely off of S3 (and maybe through Cloudfront) to get experience with that, but I'm not sure if S3 is truly ready yet.  I'll leave it to you to figure out the best way forward.  This won't take many resources on next.belframework.org since it basically acts like a static website as far as nginx is concerned.

**Comment by nbargnesi** [comment]
This is [ready for use](http://build.openbel.org/browse/BM) on the [OpenBEL Build Server](http://build.openbel.org).

Once tests and test documentation are introduced, we'll update the [test plan](http://build.openbel.org/browse/BM-TEST) piece of this and have those integrated as well.
