### ISSUE TITLE
Usersnap Feedback - Text is difficult to read on mouseover.

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#23]
**Sender**: nbargnesi@selventa.com
[Open #2 in Usersnap Dashboard](https://usersnap.com/a/#/selventa/p/belmgr-68fc8830/2)
**Notes**:
- (1) Text is difficult to read on mouseover.
- (2) Mousever text here is perfect though!

![Usersnap Feedback - Text is difficult to read on mouseover.](https://usersnappublic.s3.amazonaws.com/2015-10-06/13-27/a88dd8d7-807a-48d2-8091-95116e7dd982.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [http://belmgr.belframework.org/#/create](http://belmgr.belframework.org/#/create)
**IP**: 75.150.66.10
**Screen size**: 1280 x 800 **Browser size**: 1264 x 622

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by nbargnesi** [comment]
The usersnap image apparently didn't capture the mouseover color. Here's a screenshot from when I hovered over SEARCH:
![issue23](https://cloud.githubusercontent.com/assets/1265294/10466210/049f3850-71c1-11e5-8e54-8864cea6550e.png)

SEARCH used to show with dark text - looks okay now.
