### ISSUE TITLE
Search facet bug

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#32]
Getting weird behavior on the Search facet searches.  I'll start clicking on one, then another, then another (without unchecking any).  The second facet will cause an error, then unchecking it and checking it again - it works, third facet - same thing - broken, uncheck, recheck works - I'm getting the following 400 error associated with this when I'm first getting the checked facet error:
{
status: 400,
msg: "Invalid JSON filter: {"category":"experiment_context","name":"Cell","value":"stem cell".",
detail: "Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@352be7df; line: 1, column: 0]) at [Source: [B@352be7df; line: 1, column: 133]"
}

**Comment by abargnesi** [comment]
The 400 indicates invalid JSON was sent in a `filter` parameter.

The error indicates that the closing `}` was omitted.

**Comment by wshayes** [comment]
Thanks!
