### ISSUE TITLE
BEL statement computed as "undefined" when evidence is saved as new

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/belmgr#40]
Steps to reproduce:
1. Go to _New BEL_ screen.
2. Enter in a PubMed ID and BEL statement. For example "1131131" and a BEL statement of "AKT1", "increases", and "AKT2".
3. Hit save. In the debugger you will see this.evidence.bel_statement is computed as "undefined undefined undefined".
4. If you open "Search" and filter to that evidence (e.g. annotation or reference id) you will see a result with BEL statement "undefined undefined undefined".

**Comment by wshayes** [comment]
Fixed in commit https://github.com/OpenBEL/belmgr/commit/6e1e47774c4f24a527a5aca65dd23851b084d771
