### ISSUE TITLE
Usersnap Feedback - Added an issue where the spinner icon in the "Upload" button of the DATASE[...]

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#43]
**Sender**: abargnesi@selventa.com
**Comment**: Added an issue where the spinner icon in the "Upload" button of the DATASETS page continually spins. The only actions I did were to navigate to the DATASETS page.

Google Chrome: 48.0.2564.82 (Developer Build) (64-bit)
[Open #6 in Usersnap Dashboard](https://usersnap.com/a/#/selventa/p/belmgr-68fc8830/6)
**Notes**:
- (1) Spinner icon is always spinning (Google Chrome).

I just navigated to the "DATASETS" page without any interaction.

![Usersnap Feedback - Added an issue where the spinner icon in the "Upload" button of the DATASE(...)](https://usersnappublic.s3.amazonaws.com/2016-01-22/17-57/9944f03c-a4ce-47e2-b4bd-04a13180306f.png)

**Browser**: Chrome 48 (Linux)
**Referer**: [http://belmgr.belframework.org/#/import](http://belmgr.belframework.org/#/import)
**Screen size**: 1600 x 900 **Browser size**: 1590 x 775

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by abargnesi** [comment]
Wow, bravo usersnap.

**Comment by wshayes** [comment]
Fixed - not sure what was wrong, but it's working correctly now.
