### ISSUE TITLE
Free text search is not working

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#57]

**Comment by kellymccann91** [comment]
Need more info

**Comment by wshayes** [comment]
Please test FF and IE11 to make sure search is working on different browsers and OS.  PMI demonstrated with Windows/IE11 that search was not working on that combination.

**Comment by kellymccann91** [comment]
In IE:
- the search facets are not working
- using the search bar results in console errors:
  SCRIPT7002: Network Error, access is denied
  ERROR [openbelapi] Search API Error: TypeError" Network request failed
  ERROR [search] SEARCH ERROR:  TypeError: Unable to get property 'searchUrl' or null reference

**Comment by kellymccann91** [comment]
In Firefox:
- the search facets are not working. No console error is showing

**Comment by kellymccann91** [comment]
Update: search facets are working in Firefox and IE! :)

**Comment by kellymccann91** [comment]
Update: search textfield is working in IE.
