### ISSUE TITLE
Theme Search export and search spinner

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#63]
Theme the Search dataset export button feature and the search spinner

**Comment by kellymccann91** [comment]
Theming for the export is done - search spinner for experimental context?

**Comment by wshayes** [comment]
Search spinner - for the search page.  There is a spinner that is ugly that I inserted that works when you update the search (e.g. click on a facet checkbox and you should see it pop up at the top of the search page above the search text field).
