### ISSUE TITLE
Crash when /api/nanopubs returns 404

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/belmgr#65]
Getting nanopubs in [search.js](https://github.com/OpenBEL/belmgr/blob/master/webeditor/src/pages/search.js#L61) doesn't correctly handle the HTTP 404 case.

```
Search error  TypeError: Cannot read property 'current_page' of undefined at http://localhost:9000/dist/pages/search.js:108:40
```

Attaching Chrome devtools console output.
<img width="1169" alt="screen shot 2016-06-06 at 1 31 47 pm" src="https://cloud.githubusercontent.com/assets/1265294/15831487/e4ccedde-2beb-11e6-80ba-ca9ad1e70518.png">
<img width="1162" alt="screen shot 2016-06-06 at 1 31 56 pm" src="https://cloud.githubusercontent.com/assets/1265294/15831490/e77d178e-2beb-11e6-8455-ded1502f8fc2.png">

**Comment by wshayes** [comment]
Okay - I'll fix before tmrw
