### ISSUE TITLE
Updating of a BEL Nanopub is not working in BEL Manager

### ISSUE THREAD

**Issue by maestroe** [OpenBEL/belmgr#88]
We changed the review status of the BEL Nanopub https://pmi-belmgr.sbvimprover.com/#/edit/5873b587e4b07ff8f7a5bdff manually. After clicking the button and the success message "Updated Nanopub" appears. But reloading the page gives you the old result and shows that review status (and other fields) were not updated.

**Comment by wshayes** [comment]
Fixed in OpenBEL API
